### ISSUE TITLE
Create a folder for the React app named frontend and initialize the app

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#1]
Estimated Time: 2 hours 
This is due to needing to research how to initialize the app and then going through the initializing process.

**Comment by TimnLyt** [comment]
Acceptance criteria: 
As a developer, I want to be able to initialize the application for my team so that other developers can collaborate by adding more code.

Time Taken: 1 hour and 30 minutes
