### ISSUE TITLE
Implement simple Lambda API that handles POST

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#10]

**Comment by TurkiBK** [comment]
### User Story:

Create a lambda that accept post call.

**Estimating Time:**

50 minutes 

### Acceptance Criteria:

- Create a  lambda in AWS console.
- Accepting post requests ,and reply with 200 for successful.
- trigger it with HTTP .

**Comment by TurkiBK** [comment]
PR Document 

- Lambda was created 
![Screen Shot 2022-01-25 at 5 30 22 PM](https://user-images.githubusercontent.com/56528434/151087988-429d52ba-a45d-4b27-a9d8-30dbf6f14dc9.png)

- Trigger Lamb tonAPI ,and endpoint 

![Screen Shot 2022-01-25 at 5 31 17 PM](https://user-images.githubusercontent.com/56528434/151088093-fbf6a7a4-facc-4703-ad7d-f244ab284148.png)

End point lambda: https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda

-test the end point with postman post request 
![Screen Shot 2022-01-25 at 5 24 29 PM](https://user-images.githubusercontent.com/56528434/151088288-ffa1d4b8-84c2-4013-b366-4f6320db6b0c.png)

- The response is simple Jason file , and code stats .

**Comment by TurkiBK** [comment]
User Story:

a post request that accepts messages "input" , and responses with output.

Estimating Time:

1h minutes

Acceptance Criteria:

- post request accept input ping .
- If a reset parameter match , the response has to be pong.

**Comment by TurkiBK** [comment]
### Deception
The lambda respond successful only when the body is ping and respond with pong .
It is always respond 400 If the data not much.
It only accepts post request. 
### Time

It took me about 2.3 hours.

### Prerequisites

-Postmen or any api testing.
-Lambda endpoint.

https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda

### Post lambda code.

![Screen Shot 2022-02-03 at 5 13 45 PM](https://user-images.githubusercontent.com/56528434/152456915-80e90820-1b46-4e83-a53f-9709e0d18862.png)

### Test
-Go to postman https://www.postman.com .
-Copy the Endpoint .
-Post the endpoint on the request URL .
-Change Get to Post .
 -Select  body , row ,and change text to JSON.
-Write small Jason script that accepts argument name and select send. (e.g. {"name":"ping"})
 
### OutPut
If data matches ping return 201, if data is empty or not much the data , will response .

* when the body = ping
 
![Screen Shot 2022-02-03 at 7 13 21 PM](https://user-images.githubusercontent.com/56528434/152466328-34911732-1dfb-4fd6-9d7b-f43b228799ea.png)

* when the body != p

![Screen Shot 2022-02-03 at 7 13 43 PM](https://user-images.githubusercontent.com/56528434/152466393-5ac03a62-76cf-44c5-ac84-9dbb002902d9.png)

* when the body  is empty = ""

![Screen Shot 2022-02-03 at 7 14 01 PM](https://user-images.githubusercontent.com/56528434/152466437-0cab0728-b2a7-4f59-b125-d2737e9e2db9.png)
