### ISSUE TITLE
Fix the response body from the API to not include information from the header

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#113]
# User Story
As a developer, I want to return just the body property, so that users calling the route don't get any unnecessary information

# Estimated Time to Complete
2 hours

# Additional Context
The following implementation from #109 has a bug that it returns information that doesn't belong in the body. The current response is:
```
{"statusCode":200,"body":"[{\"sentence\":\"No full sentences detected. Sentences must end with punctuation of either a period (.), exclamation point (!), or question mark (?), to be considered full sentences.\",\"type\":\"No full sentences detected to detect type. Sentences must end with punctuation of either a period (.), exclamation point (!), or question mark (?), to be considered full sentences.\",\"sentiment\":\"No full sentences detected to determine sentiment. Sentences must end with punctuation of either a period (.), exclamation point (!), or question mark (?), to be considered full sentences.\"}]","headers":{"Content-Type":"application/json"}}
```

The only thing that should've returned is the array from the `body` property.

# Acceptance Criteria
- [x] The only thing returned by this route should be the array from the body property

**Comment by dansjack** [comment]
# Activities Documentation


| Date  | Activity | Time Spent |
| ------------- | ------------- | ------------- |
| 03/06/2022 | Research API gateway, lambda functions | 2 hr  |
| 03/06/2022 | Update script to remove headers and status code | 0.5 hr  |
| 03/06/2022 | Set up test API trigger for simplePostLambda | 0.5 hr |
| 02/16/2022 | Documentation + Testing | 0.5 hr |
