### ISSUE TITLE
SageMaker ML model for splitting the feedback in sentences

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#118]

**Comment by TurkiBK** [comment]
### User story
Ml that split the feedback to sentences.
- Create a lambda that take feedback as  string and spilt it to separate sentences.
- Input  {"feedback" : " Hi ,  it is. a good job . What is m;y next task ? I do not know where to find it . Something here , and here !"}.
- output   {"sentence " : " Hi ,  ,  it is. a good job . ,  What is m;y next task ? ,  I do not know where to find it . ,  Something here , , and here ! ,"}
 
Estimate time 
2-3 hours .
