### ISSUE TITLE
Write export script for the data to export from Firebase

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#12]

**Comment by dale108** [comment]
Link to the pull request: https://github.com/North-Seattle-College/ad440-winter2022-tuesday-repo/pull/17

Time to complete:
- This was trickier than it looked - Google has not produced good documentation on how to access firebase in this manner, and how to traverse the tree of collection - documents for a given schema. I tied a few approaches, which worked, such as writing a bash script with username/password auth, but it would not have been reuseable for floop, so I attempted to work out something in python.

Outcome:
- Floop has run this script in their production environment, and it did what it was supposed to do - pulled data and saved it to a json file. 

Documentation:
   - go to the floop firebase account and generate a cert file
   - run the script, and input the path to the cert file you generated in the previous step
   - the script will generate a file, floop_data.json upon completion

**Comment by toddysm** [comment]
It will be good to know where the exported file can be found. We can create a restricted bucket in S3 and upload the file there. People who need the data can either download to their machines and use it or if they are developing automation scripts for import, they can read from the bucket itself.

**Comment by dale108** [comment]
HI @toddysm I shared this on Slack, but not here. I created a restricted access bucket when I merged the script https://floop-dataset.s3.us-west-2.amazonaws.com/floop_data_15k.json
