### ISSUE TITLE
Configure SageMaker ML model for splitting the feedback in sentences to be accessible via API

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#121]
Refer to #118

**Comment by Annelisebx** [comment]
**User Story**
Goal: To be able to call the SageMaker model for splitting the feedback into sentences using Amazon API Gateway and AWS Lambda Function.

**Estimated time to complete**
15 hours

**Acceptance Criteria**
- [ ]  AWS Lambda Function sets endpoint made by SageMaker Model 
- [ ]  API Gateway calls Lambda Function specifying the endpoint with created SageMaker Notebook Instance
- [ ]  API Gateway is deployed calling the Lambda Function and the SageMaker Endpoint


### Activities Documentation
<html>
<body>


Date | Activity | Time Spent
-- | -- | --
3/06/2022 | Researching SageMaker Endpoints and Notebook Instances | 3 Hours
3/08/2022 |  Reviewing [Example](https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/) | 2 Hours
3/13/2022 | Creating Endpoint and API Gateway with Lambda Function | 2 Hours
3/14/2022 |  Creating Endpoint and API Gateway with Lambda Function | 5 Hours



</body>
</html>


**Pull Request**
- Unsure I need a PR. Gateway was called with POST method created that is connected to split sentence SageMaker Model and Lambda Function.
- Moving to complete
