### ISSUE TITLE
Configure the feedback classification model on SageMaker to be accessible via API

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#125]
See #124 

Time Estimated to Complete Issue: 
## Estimated Time:
| Tasks | Time |
| ------------- | ------------- |
| Team Meetings/Discussions | 2 hrs |
| Research | 2-4 hrs |
| Configuring feedback classification model | 1 hr  |
| Create the PR/Other Documentation | 1-2 hrs |
| Total | 6-9 hrs

**Comment by TimnLyt** [comment]
Acceptance Criteria:
As a developer, I want to be able to have the feedback classification model that's on SageMaker be accessible via API.   

Time Taken: 
## Time Spent on Issue:
| Tasks | Time |
| ------------- | ------------- |
| Team Meetings/Discussions | 2 hrs |
| Research | 6 hrs |
| Configuring feedback classification model | 1 hr  |
| Create the PR/Other Documentation | 2 hrs |
| Total | 11 hrs

No PR needed for this issue

### Documentation:

### Gallery:

**_Amazon API Gateway_** 
![Screenshot (409)](https://user-images.githubusercontent.com/73623897/159189501-573974c0-ffd5-4ad2-9eaa-f060f5f3e29f.png)

**_Feedback Classification with API Gateway connected_** 
![Screenshot (415)](https://user-images.githubusercontent.com/73623897/159189528-3e988305-1a98-45b8-8439-d1a7c6522de1.png)

**_After URL is clicked_** (Expected)
![Screenshot (414)](https://user-images.githubusercontent.com/73623897/159395317-d2bad929-0c5a-4e49-9d7c-9b0466958599.png)

### Troubleshooting for app:

To start the app:
You have to type `npm start` when in the src file. Then the application should open up in a new window.
