### ISSUE TITLE
Explain the application architecture and how the data flows

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#147]
The explanation should include:

- What happens when the URL from #146 is loaded in the browser
- What is the data flow

**Comment by Annelisebx** [comment]
**User Story**
Goal: To effectively and efficiently present to the Floop Team the architecture of our AWS model and describe how the data flows between elements. 

**Key Points**
- [ ] User/Client
- [ ] URL and domain name
- [ ] API Gateway
- [ ] Lambda Resources
- [ ] SageMaker Models
- [ ] Jupyter Notebooks

**Estimated time to complete**
1 Hour

**Acceptance Criteria**
- [ ]  Effectively explains the architecture of our AWS model and accurately shows how data flows through different elements

### Activities Documentation
<html>
<body>


Date | Activity | Time Spent
-- | -- | --
3/20/2022 | Studying diagram made in class on 3/15 | .5 Hour
3/21/2022 | Review diagram and discuss architecture with Kristin | 1 hour



</body>
</html>

**Pull Request**
No PR required. Completed in class demo on 3/22/22
