### ISSUE TITLE
Develop the component for submitting the feedback to the server

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#15]
# User Story

As a developer I want to create some components, then I can use them for submitting the feedback and add backend function for testing purpose 

# Acceptance Criteria

Create components that user can input texts, and user able to show the text to the feedback field by click on the submit button.

# Pull Request

#26

**Comment by zaks2318** [comment]
| Task Breakdown Description      | Approx. Time |
| ----------- | ----------- |
| Researching for AI feedback components     | 1 hour       |
| Setting up React Environment   | 1 hour        |
| design the components   | 1 hour        |
| coding for the components | 4 hours        |
| testing the components   | 0.5 hour        |
| change and fix some code after group discuss   | 1 hour        |
| add few comments and style to components | 0.5 hour        |
| Frontend Team Meets | 3 hours        |
