### ISSUE TITLE
Replace the POST endpoint in the React app to use the official one

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#155]
We should call `https://api.holodium.com/v1/feedback` from the React app. Make sure it is working for the demo and passes the CORS check

**Comment by mfern08** [comment]
### User Story
As a developer, I want to see if the response from the updated API works and can be displayed to be demo ready. 
As a user, it would be helpful to see the comment to my responses to improve my feedback to the students.

### Acceptance Criteria

- [ ] view analysis response on UI when feedback is sent

### Estimated & Time Spent total
Estimated: 3 hours 
Time spent total: 14.65 hours

### Time Spent on Issue
|  Activity | Time Spent |
| ------------- | ------------- |
| Team Meetings | 2 hrs  |
| CORS Research | 5 hr  |
| Troubleshooting with CORS | 7 hr  |
| Coding | 0.16 hr |
| Testing | 0.5 hr |
