### ISSUE TITLE
Test the API with valid and invalid input

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#158]
You should use curl and test the frontend API `https://api.holodium.com/v1/feedback` with valid and invalid input.

Document all the calls that are made including the input and the output.
Do at least 5 test for each of the cases (valid input and invalid input)

Time Estimated to Complete Issue: 
## Estimated Time:
| Tasks | Time |
| ------------- | ------------- |
| Team Meetings/Discussions | 2 hrs |
| Research | 2-4 hrs |
| Test frontend API using curl | 2 hrs  |
| Create the PR/Other Documentation | 1-2 hrs |
| Total | 7-10 hrs

**Comment by TimnLyt** [comment]
Acceptance Criteria:
As a developer, I want to e able to test different kinds of input (both valid and invalid) to see the outputs of the program. 

## Time Taken:
| Tasks | Time |
| ------------- | ------------- |
| Team Meetings/Discussions | 2 hrs |
| Research | 4 hrs |
| Test frontend API using curl | 3 hrs  |
| Fixing Errors | 2 hrs |
| Create the PR/Other Documentation | 2 hrs |
| Total | 13 hrs

No PR needed for this issue

### Documentation & Gallery:

SUCCESS (statement) 
curl -d '{"feedback": "YOUR_SENTENCES_HERE."}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (425)](https://user-images.githubusercontent.com/73623897/159397324-25db111c-a3ee-4deb-96b7-6c26b49ff7cc.png)

SUCCESS (question)
curl -d '{"feedback": "YOUR_SENTENCES_HERE?"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (431)](https://user-images.githubusercontent.com/73623897/159397662-1d759100-be26-4711-8393-1a8d090c3bb7.png)

SUCCESS (exclamation)
curl -d '{"feedback": "YOUR_SENTENCES_HERE!"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (433)](https://user-images.githubusercontent.com/73623897/159397805-edaab18c-5b5c-4774-9a9c-2146e2e3adb1.png)

SUCCESS (multiple sentences)
curl -d '{"feedback": "This is some words. More words."}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (435)](https://user-images.githubusercontent.com/73623897/159397981-350f2dd6-6bf5-4fc1-a873-098e0076dd66.png)

SUCCESS (positive statement)
curl -d '{"feedback": "Pretty good."}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (437)](https://user-images.githubusercontent.com/73623897/159398393-36aa44ad-f499-4e8f-8b16-315384747ace.png)

ERROR no full sentence detected (just letters) (just numbers) (just symbol)
curl -d '{"feedback": "ABC"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
curl -d '{"feedback": "123"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/ 
curl -d '{"feedback": "*"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (440)](https://user-images.githubusercontent.com/73623897/159399125-bce3b2af-eb59-4b1d-bda8-433a0ccea7c0.png)

### Things that need to be fixed:

STANGE OUTCOMES WITH SUCCESS ("Not good" caught as a positive comment) ("Not bad" caught as negative comment)
![Screenshot (426)_LI](https://user-images.githubusercontent.com/73623897/159399214-34f4ba34-1767-4088-99b2-
4505b602780d.jpg)
![Screenshot (428)_LI](https://user-images.githubusercontent.com/73623897/159399322-8904f2d3-3622-46d7-8fdc-36f4b654af7d.jpg)

("Pretty bad" fixes this issue and is caught as a negative comment) ("bad" uppercase or lowercase is caught as a neutral comment)
![Screenshot (430)_LI](https://user-images.githubusercontent.com/73623897/159399474-06627d77-7744-4df6-95f4-1eb7b56f269b.jpg)

(Punctuations can be used on their own without a sentence)
curl -d '{"feedback": "!"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (445)](https://user-images.githubusercontent.com/73623897/159400293-a28dcabc-732f-496a-be07-f729009977cc.png)

(Punctuations don't have to be in front of the word to work)
curl -d '{"feedback": "!Words"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (443)](https://user-images.githubusercontent.com/73623897/159400082-7fc8e4dd-3812-4aec-ab0b-05b2eaedf02f.png)

(Punctuations can be together without any sentence and still work)
curl -d '{"feedback": ".!?"}' -H "Content-Type: application/json" -X POST https://api.holodium.com/
![Screenshot (447)](https://user-images.githubusercontent.com/73623897/159400571-575ea3eb-381c-4851-bc7c-d110a34c5c3a.png)

### Troubleshooting for testing with curl:

Make sure to not type out the command but instead copy and paste it into the console. Usually it fixes the problem but sometimes you'll get this error and will need to paste it a few more times to have it work. 
![Screenshot (420)_LI](https://user-images.githubusercontent.com/73623897/159401433-043a14b2-e924-447a-8ce8-4cfeeca5a7c3.jpg)

### Troubleshooting for app:

To start the app:
You have to type `npm start` when in the src file. Then the application should open up in a new window.
