### ISSUE TITLE
Create a GitHub action to deploy the code handling POST requests to the Lambda function resource

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#24]

**Comment by Annelisebx** [comment]
**User Story**
Create a new action in Github that will automatically deploy the code with POST requests to the Lamba function resource.

**Estimated time to complete**
8 hours

**Acceptance Criteria**
- [ ]  New Github action created
- [ ] Action deploys changes from code handling POST requests
