### ISSUE TITLE
Improve the automation for the creation of S3 bucket to be machine runnable

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#40]
### User Story
As a developer, I want to modify the script from issue #7 to be machine runnable, so I don't need an active user to follow the prompts to create the resource.

### Estimated time to complete
4 hours

### Acceptance Criteria
- [x] Update script to be able to run without user input
    - [x] Script should accept a command line argument, initials
    - [x] Script should validate the initials argument, whether it's passed in as a command line argument, or through the user prompt

**Comment by dansjack** [comment]
# Activities Documentation


| Date  | Activity | Time Spent |
| ------------- | ------------- | ------------- |
| 02/02/2022 | Researching ability to call shell function from anywhere | 1 hr  |
| 02/02/2022 | Researching shell variables, functions, and coding conventions  | 2 hr  |
| 02/02/2022 | Updating script  | 1 hr  |
| 02/02/2022 | Testing | 0.5 hr  |
| 02/03/2022 | Documentation | 0.5 hr  |
