### ISSUE TITLE
Integrate the Lambda creation into the Lambda deployment action

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#42]
See #11 for automation of the Lambda resource and #24 for the GitHub action. Both need to work in concert - when a new code gets pushed to branch X, the Lambda resource gets created and the code is deployed.

**Comment by Annelisebx** [comment]
**User Story**
Integrate the code that creates the Lambda Function into the script that deploys the change through GitHub Actions. 


**Estimated time to complete**
15 hours

**Acceptance Criteria**
- [ ]  Creates Lambda Function
- [ ] New code is deployed to the same created Lambda Function in one push. 

### Activities Documentation
<html>
<body>


Date | Activity | Time Spent
-- | -- | --
02/07/2022 | Researching integration of Lambda function to script, reviewing code creating function| 1 Hour
02/15/2022 | Adding copy's of Lambda creation script to scripts file | 2 Hours
02/16/2022 | Editing files in scripts file, editing .yml workflow file to incorporate script files | 2 Hours
02/19/2022 | Researching and setting GitHub environment variables in scripts | 3 Hours
02/20/2022 | Continue to edit environment variables in create and deploy scripts | 5 Hours
02/22/2022 | change creation script file from .sh to .bash | 3 Hours


</body>
</html>
