### ISSUE TITLE
Create a Sage Maker resource and run the clustering algorithm on it

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#45]
See #22

**Comment by Lola2018** [comment]
I have run the code in #22 and made the following changes:

1. Replaced the input code to pick up the floop_data_15k.json file from SageMaker resource
2. Created a python notebook to run the code in SageMaker

The output we got was as below:
![image](https://user-images.githubusercontent.com/44072547/152669182-3bf8bef7-d331-431e-80b5-521cfd15e983.png)

**Comment by Lola2018** [comment]
**Task Description**
Create a SageMaker resource and run clustering algorithm on it.

**Activities Involved**
1. Creating SageMaker Resource: 2 hours
2. Setting up Jupyter notebook in SageMaker, installing libraries required: 1 hour
2. Migrating code developed by #22 and making modifications for SageMaker: 2 hours

**Instructions to run in SageMaker**
1. Open the notebook in SageMaker
2. Go to Run -> Select "Run all cells" for the selcted notebook
3. Wait for cells to run and output to be shown. (Video shown below)


**Status**
I have finished coding the sagemaker clustering algorithm, and the results are coming as expected.
I am currently trying to push these into github.

https://user-images.githubusercontent.com/44072547/153701129-af82250e-fc9d-4a4f-bbce-d16573657fb7.mp4
