### ISSUE TITLE
Change the POST API to accept the teachers feedback

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#46]
Look at the Swagger and what is specified there. Work with Alas to make sure you implement the Swagger in your API.

**Comment by TurkiBK** [comment]
### User Story
Modify the lambda to receive a post teacher feedback.Implement and import swagger in the lambda. 
### Estimated time 
1 hour.
### Acceptance Criteria
 Input Id, and teacher feedback as json . 
 Output successful post feedback.
