### ISSUE TITLE
Investigate how to use GitHub actions to deploy React to S3

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#8]
## User Story
As a developer I want to know how to deploy the React App to a S3 Bucket utilizing GitHub Actions

## Acceptance Criteria
- [x]  Research GitHub action implementation to learn about the process needed for deployment

## Pull Request
#27 
Documentation, and all other details can be found on the linked PR 

### Estimated Time:
8 hours 

### Actual time spent:
13 hours (This includes Frontend team meetups)
_(See hours breakdown on the PR, linked above)_

**Comment by ChrisNavoczynski** [comment]
## Time Spent on Issue:
| Task Breakdown Description | Approx. Time |
| ------------- | ------------- |
| Researching Deployment Resources | 2 hrs |
| Setting up React | 1 hr  |
| Compile the References to one easy to follow instruction  | 0.5 hr  |
| Testing Part 1: Create a test Repo, and React App | 1 hr  |
| Testing Part 2: Create a test S3 Bucket | 0.5 hr  |
| Testing Part 3:  Setup the Github Secrets and Workflow | 2 hrs | 
| Create the .md file and documentation folder in the frontend folder | 2 hrs |
| Create the PR with additional information and follow-along screenshots | 1 hr |
