### ISSUE TITLE
Improve the error handling of the POST API

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#81]
Right now, the POST API doesn't handle improper input (like empty input or non JSON input that is valid). We need to improve the error handling for those conditions. Here are sample requests that you can use for testing:

```
curl -X POST -d "" -H "Content-Type: application/json" -v https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda
curl -X POST -d "asdfasdfasdfasfd" -H "Content-Type: application/json" -v https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda
  curl -X POST -d "{\"someprop\":\"someval\"}" -H "Content-Type: application/json" -v https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda
```

**Comment by TurkiBK** [comment]
### User Story 
Improving Api to handle a correct input data.The API would only mange and process a right Info.API has to make suer, and return errors when the event , is empty , or contain unmatched data.
 
### Estimated Time to Complete:
2 h

**Comment by TurkiBK** [comment]
### To test it

Prerequisites 
* Endpoint : https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda

### Using postmen or smiler 

1. Copy the endpoint and post it on the postmen url
2. Change method from get to post
3. select body, raw ,and change text to JSON
4. sending json as {"feedback":"write something here "} 
5. click send 
6. getting response with 201 when it is succeed.
7. getting response 400 for empty string 

### Using terminal 

1.   % curl -d '{"feedback":"Good job!"}' -H "Content-Type: application/json" -X POST https://p9y9bbcruj.execute-api.us-west-2.amazonaws.com/default/simplePostLambda
2. getting response with 201 when it is succeed
3. getting  response 400 for empty string 

*It only accepts {"feedBack":"write something here "} syn , other way , it will sends errors.
It is not mange any get error therefore it will get you empty feed back , I am working to solve that .


### Gallery
 When the syntax is correct 
![feedBack](https://user-images.githubusercontent.com/56528434/155239453-3db3353b-7ac3-4c0e-94d7-e2e6cc63fba1.png)

 When the syntax is dose not have a feedback.
![Screen Shot 2022-02-22 at 3 58 54 PM](https://user-images.githubusercontent.com/56528434/155240138-5b3dfbff-e139-4954-b444-bf86d625a444.png)

 When the syntax is incorrect and not follow syntax.
![Screen Shot 2022-02-22 at 4 01 56 PM](https://user-images.githubusercontent.com/56528434/155240428-1b336536-d0be-412e-b0e8-8161bfac3765.png)

**Comment by TurkiBK** [comment]
Close issue #81
### Documentation 
This final version of sample lambda .The lambda is only accepts post requests and only teacher feedback.It also handling errors  and turns errors stats code such as wrong sys ,or missing string.
The file can be found in backend >>simpleLambda.
To test the lambda , the instructor at the top.

![Screen Shot 2022-03-06 at 4 36 28 PM](https://user-images.githubusercontent.com/56528434/156949708-8c08deaa-b549-4c89-afe3-0453e8d1ef06.png)
