### ISSUE TITLE
Expose the SageMaker clustering algorithm as API

### ISSUE THREAD

**Issue by toddysm** [North-Seattle-College/ad440-winter2022-tuesday-repo#85]
For this task we would like to expose the clustering algorithm deployed in #45 as an API that has the following:
- Input is the location of the data in an S3 bucket
- The output is the following JSON

```
{ "numberOfClusters": "xxxx"}
```
Where `xxxx` is how many clusters the algorithm recognized.

**Comment by Eftu-Wakjira** [comment]
**Description**:
Here, I modified the previous KMeans clustering algorithm created on sklearn, and deployed it on SageMkaer.
The outputs and inputs of the SageMaker clustering have been modified to pick up and save the output in S3 buckets.

The bucket created in S3 is as follows:
![image](https://user-images.githubusercontent.com/44072547/156490114-e54a18ba-c03d-4c81-9a0a-857217d7ace6.png)

The json file input is located as shown above.
In the same bucket, I have another json file as highlighted below that stores the output in the required format as expected by @toddysm: a JSON file with { "numberOfClusters": "xxxx"} 

the output is shown as below
 
![image](https://user-images.githubusercontent.com/44072547/156489688-10ef3a4d-8e0c-4f4c-ba6f-95c861f9e2c2.png)

The output is shown number of cluster is 2 as below picture
![image](https://user-images.githubusercontent.com/44072547/156490728-b8326e60-dcd8-43bf-a596-ccb90f210413.png)
